### ISSUE TITLE
Execution summary is not displayed

### ISSUE THREAD

**Issue by zastress** [joonvena/robotframework-reporter-action#14]
I have this piece of code running on Github actions:

```
generate_report:
        if: always()
        needs: [Run-Api-Tests] 
        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v2
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports
        - name: Send report to commit
          uses: joonvena/robotframework-reporter-action@v2
          with:
            gh_access_token: ${{ secrets.TOKEN }}
            summary: true
```

According to the documentation, adding `summary: true` should output the test summary but I get this error inside the Action output: `Unexpected input(s) 'summary', valid inputs are ['gh_access_token', 'report_path', 'sha', 'pull_request_id']`
