### ISSUE TITLE
Cannot access the summary file - permission denied

### ISSUE THREAD

**Issue by MassiveMaker** [joonvena/robotframework-reporter-action#21]
Hi guys,

During the "Send report to commit" step, we are getting a "permission denied" error when trying to access a summary file. As far as I can see on the server, the file has permission 644, so theoretically, it should be accessible.

Has anyone encountered this issue before?

```
Run /opt/actions-runner/_work/_actions/joonvena/robotframework-reporter-action/v2.1/report.sh

2023/06/08 13:25:47 open /opt/actions-runner/_work/_temp/_runner_file_commands/step_summary_7e756204-7af3-4e92-9c2a-ccaa7f359f37: permission denied

2023/06/08 13:25:47 invalid argument
```

workflow:
```
  generate_report:
    if: always()
    needs: [ tests ]
    runs-on: [ "self-hosted","linux","x64","test-runners" ]
    steps:
      - uses: actions/checkout@v2
      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: reports
      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
```
