### ISSUE TITLE
SHA string gets double quotes around it when used through an artifact

### ISSUE THREAD

**Issue by jazmc** [joonvena/robotframework-reporter-action#24]
Hiya!

I'm attempting to use this action to comment robot logs to a commit. The repository is a fork, so due to permission issues I have to upload the commit's SHA number as an artifact from the testing workflow, and pass it to the separate robot log reporting workflow.

I'm currently getting this error:
```sh
2023/08/23 11:11:06 POST https://api.github.com/repos/{organisation and repository}/commits/%223b9fc46f01591b84c4950f6ec53f00b3614591c%22/comments: 422 No commit found for SHA: "3b9fc46f01591b84c4950f6ec53f00b3614591c" []
Error: Process completed with exit code 1.
```

The `%22` in the url tells that there are extra quotes around the sha number when passed to your action, but I have not come to a solution where I could remove them on my end. Workflow file parses the SHA number as follows:

```yaml
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "sha"
            })[0];
            var download = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/sha.zip', Buffer.from(download.data));
      - run: unzip sha.zip
      - name: 'Get sha Number'
        id: fetch_sha
        uses: actions/github-script@v6
        with:
          script: |
            var fs = require('fs');
            var issue_number = String(fs.readFileSync('./NR'));
            return issue_number.slice(0, -2).toString();
          # parses commit sha from artifact, removes \n from the end of the string
      - name: 'Send report to commit'
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          report_path: reports
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          show_passed_tests: true
          sha: ${{steps.fetch_sha.outputs.result}}
```

The `${{steps.fetch_sha.outputs.result}}` variable apparently uses JSON.stringify which adds quotes around a string variable.
In your `action.yml` the SHA number is used like this...
```yaml
COMMIT_SHA: "${{ inputs.sha }}"
```
... which I am guessing might be the reason it is getting double-quoted..?

So, questions:
- Can anyone suggest any solution I could do on my end to get around this problem? And if not,
- Could you remove the quotes around `${{ inputs.sha }}` variable on `action.yml`, or add some conditional formatting in it to prevent double-quotes around the variable?

Thank you in advance! 💯

**Comment by joonvena** [comment]
You can change the result-encoding in the actions/github-script. By default it will use json output which means that it will use `JSON.stringify(value)` and you pass string to it which then adds the double quotes `'"<value>"'` This should fix the issue:

```
- name: 'Get sha Number'
  id: fetch_sha
  uses: actions/github-script@v6
  with:
      result-encoding: string
      script: |
      ...
```
