### ISSUE TITLE
[Feature request] Support reporting to a PR from another repository

### ISSUE THREAD

**Issue by lachaib** [joonvena/robotframework-reporter-action#25]
Hello,

In my current organisation, we've got a specific repository (say `robot-tests`) containing robot framework tests and corresponding secrets. In order to run those tests after deployment of any service stored in other repositories (`serviceA`,  `serviceB`), I need to *dispatch*  a workflow. I insist on the `workflow_dispatch` event because the `workflow_call` event from another repo cannot access secrets stored for `robot-tests` repository (and it's a bad practice to store everything at organisation level).

Therefore, I would like to enable this action to support passing another repository as input.

Following what I could see in the action code, the simplest way would be to add
```yaml
repository:
    type: string
    description: Repository ([Owner/]Repository) of pull request to decorate with report
    default: "${{github.repository}}"
```
and modify the bash step to parse it instead of direct parsing of `${{github.repository}}`

I will make a PR accordingly if you agree with it.
