### ISSUE TITLE
Not able to find report.sh

### ISSUE THREAD

**Issue by coderdeepdotcom** [joonvena/robotframework-reporter-action#38]
While running the workflow file mentioned below. I am receiving error :/__w/_temp/9ef1985b-745a-4c17-b6bb-ba7eaca5bb0e.sh: line 1: /opt/actions-runner/_work/_actions/joonvena/robotframework-reporter-
action/229b6d4248b20be6e54f4fc32c7414130d1bf200/report.sh: No such file or directory

I have executed the report upload part with windows and report download and generation in ubuntu as suggested in a previous thread but still it didn't work.

```
name: Test Cloud Runner

on:
  schedule:
    - cron: 0 0 * * *
  
  workflow_dispatch:

jobs:
  Run-Tests:
    timeout-minutes: 50000
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install playwright
      - name: Install playwright Browsers
        run: python -m playwright install --with-deps
      
      - name: Execute tests
        run: |
          cd ${{ github.workspace }}
          robot -d ./Test-Results -i Regression ./Tests/Login.robot
          
      - name: Test Report Upload
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test-Results
          path: Test-Results
          
  generate_report:
    needs: Run-Tests
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Download reports
        uses: actions/download-artifact@v1
        if: always()
        with:
          name: Test-Results
          
      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@229b6d4248b20be6e54f4fc32c7414130d1bf200
        if: always()
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report_path: Test-Results
          only_summary: true
```

![issuereporter](https://github.com/user-attachments/assets/1abd8a26-b93c-4604-8e83-93325f65db25)
